default: true

# MD004/ul-style - Unordered list style
MD004:
  # List style
  style: "dash"

# MD007/ul-indent - Unordered list indentation
MD007:
  # Spaces for indent
  indent: 4

# MD013/line-length - Line length
MD013: false

# MD024/no-duplicate-heading/no-duplicate-header - Multiple headings with the same content
MD024:
  # Only check sibling headings
  siblings_only: true

# MD028/no-blanks-blockquote - Blank line inside blockquote
MD028: false

# MD046/code-block-style - Code block style
MD046:
  # Block style
  style: "fenced"

# MD049/emphasis-style - Emphasis style should be consistent
MD049:
  # Emphasis style should be consistent
  style: "asterisk"

# MD050/strong-style - Strong style should be consistent
MD050:
  # Strong style should be consistent
  style: "asterisk"
